# Generated by Django 5.0.3 on 2024-04-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0002_strike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
