# Generated by Django 5.0.3 on 2024-04-26 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0005_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
