# Generated by Django 5.0.3 on 2024-04-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0006_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=1000),
        ),
    ]
