# Generated by Django 5.0.3 on 2024-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0007_alter_phrase_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
