# Generated by Django 5.0.3 on 2024-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0008_phrase_learned_word_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='A1', max_length=100),
        ),
    ]
