# Generated by Django 5.0.3 on 2024-05-04 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0009_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='last_strike',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
