# Generated by Django 5.0.3 on 2024-05-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0010_strike_last_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
