# Generated by Django 5.0.3 on 2024-05-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0011_grades_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='', max_length=100),
        ),
    ]
